project:
  type: website
  output-dir: docs

website:
  title: "Katrina Johnson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

