<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>K Johnson - Brain Gain Question List</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">K Johnson</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resources.html" rel="" target="">
 <span class="menu-text">Resources</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Date Money (z-score)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>This list of problems focus on computations and concepts that students have a tendency of mixing up or need additional practice. These problems are intended the to be used as interleaved retrievel practice at the beginning of class to keep the concepts fresh in students minds throughout the semester.</p>
<p>As the problems are selected the box can be checked and a note can indicate which week/day it was used. It is probably okay to use problems more than once as long as there is some time between uses.</p>
<section id="after-lesson-1" class="level1">
<h1>After Lesson 1</h1>
<section id="probability-rules" class="level2">
<h2 class="anchored" data-anchor-id="probability-rules">Probability Rules</h2>
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Probability Rules Error Identification</li>
</ul>
<p>What’s wrong with the statement, “There is a 1.2 probability of snow in January in Rexburg”?</p>
<details>
<summary>
Possible Solution
</summary>
<p>A probability is a number between 0 and 1, <span class="math inline">\(0 \leq p \leq 1\)</span>. The probability of snow cannot be 1.2 because <span class="math inline">\(1.2 \nleq 1\)</span> (rather 1.2 &gt; 1).</p>
</details>
<!--- From my 221 Wiki April 21, 2021 --->
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Snow in May</li>
</ul>
<p>Suppose the probability of snow in Rexburg in May is 0.79. What is the probability of no snow in Rexburg in May?</p>
<details>
<summary>
Possible Solution
</summary>
<p>1-0.79 = 0.21</p>
<p>The probability that there will be no snow in Rexburg in May is 0.21.</p>
</details>
<!--- From my 221 Wiki April 21, 2021--->
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Tokens</li>
</ul>
<p>A box of tokens contains 8 blue tokens, 6 red tokens, and 4 yellow tokens.</p>
<p>If a token is selected at random from the box, what is the probability that the token is blue?</p>
<details>
<summary>
Possible Solution
</summary>
<p>P( token is blue ) = <span class="math inline">\(\frac{8}{8+6+4} = \frac{8}{18} = \frac{4}{9} = 0.\overline{4}\)</span></p>
</details>
<p>If a token is selected at random from the box, what is the probability that the token is not red?</p>
<details>
<summary>
Possible Solution
</summary>
<p>P( token is red ) = <span class="math inline">\(\frac{6}{18} = 0.\overline{3}\)</span></p>
<p>P( token is NOT red ) = <span class="math inline">\(1 - 0.\overline{3} = 0.\overline{6}\)</span></p>
</details>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"><!--- From my 221 Wiki April 21, 2021---></h2>
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Blood Type</li>
</ul>
<p>The probability that a randomly chosen North American has a particular ABO blood type and Rh factor is given below.</p>
<p><em>Source: “The Analysis of Biological Data” by Whitlock and Schluter, 3rd Edition, page 125.</em></p>
<table class="table">
<thead>
<tr class="header">
<th>Blood Type</th>
<th>Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>O+</td>
<td>0.374</td>
</tr>
<tr class="even">
<td>O-</td>
<td>0.066</td>
</tr>
<tr class="odd">
<td>A+</td>
<td>0.357</td>
</tr>
<tr class="even">
<td>A-</td>
<td>0.063</td>
</tr>
<tr class="odd">
<td>B+</td>
<td>0.085</td>
</tr>
<tr class="even">
<td>B-</td>
<td>0.015</td>
</tr>
<tr class="odd">
<td>AB+</td>
<td>0.034</td>
</tr>
<tr class="even">
<td>AB-</td>
<td>0.006</td>
</tr>
</tbody>
</table>
<ul>
<li><p>What is the probability that a randomly selected North American, will have blood type A?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>P( has type A+ ) + P( has type A- ) = 0.357 + 0.063 = 0.42</p>
<p>The probability that randomly selected North American will have type A blood is 0.42.</p>
</details></li>
<li><p>What is the probability that a randomly selected North American, will ’‘’not’’’ have O+ blood type?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>1 - P( has type 0+) = 1 - 0.374 = 0.626</p>
<p>The probability that a randomly selected North American will not have O+ blood is 0.626.</p>
</details></li>
</ul>
<!--- From my 221 Wiki April 21, 2021--->
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> 3 Coin Flips</li>
</ul>
<p>If you flip a fair coin 3 times you could get either 0, 1, 2, or 3 heads with the following probabilities.</p>
<table class="table">
<thead>
<tr class="header">
<th>0 Heads</th>
<th>1 Head</th>
<th>2 Heads</th>
<th>3 Heads</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\frac{1}{8}\)</span></td>
<td>??</td>
<td><span class="math inline">\(\frac{3}{8}\)</span></td>
<td><span class="math inline">\(\frac{1}{8}\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><p>What is the probability that you will get 1 head in the three tosses?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>P( 1 head ) = 1 - P( not 1 head) = 1 - (1/8 + 3/8 + 1/8) = 1 - 5/8 = 3/8</p>
</details></li>
<li><p>What is the probability you will not get (exactly) 2 heads in the three tosses?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>1 - P( 2 heads ) = 1 - 3/8 = 5/8</p>
</details></li>
</ul>
<!--- From my 221 Wiki April 21, 2021--->
</section>
</section>
<section id="after-lessons-3-and-4" class="level1">
<h1>After Lessons 3 and 4</h1>
<section id="mean-and-median" class="level2">
<h2 class="anchored" data-anchor-id="mean-and-median">Mean and Median</h2>
<ul>
<li><p><input type="checkbox"><strong>Problem:</strong> Comparing Mean and Median</p></li>
<li><p>Consider the following data set 6, 58, 100.</p>
<ul>
<li><p>Calculate the mean.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(\overline{x} = \frac{6 + 58 + 100}{3} = 54.\overline{6}\)</span></p>
<p>The mean of the data is <span class="math inline">\(54.\overline{6}\)</span>.</p>
</details></li>
<li><p>Calculate the median.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The data set in order is 6, 58, 100. We see the middle value is 58.</p>
<p>The median of the data is 58.</p>
</details></li>
<li><p>Suppose the 6 was a typo and was actually supposed to be a 60.</p>
<ul>
<li><p>What is the mean of the corrected data? Did the mean increase, decrease, or stay the same when <strong>one</strong> number in the data changed?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(\overline{x} = \frac{60 + 58 + 100}{3} = 72.\overline{6}\)</span></p>
<p>The mean of the corrected data is <span class="math inline">\(72.\overline{6}\)</span>.</p>
<p><span class="math inline">\(72.\overline{6} &gt; 54.\overline{6}\)</span></p>
<p>The mean increased.</p>
</details></li>
<li><p>What is the median of the correct data? Did the median increase, decrease, or stay the same when <strong>one</strong> number in the data changed?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The corrected data set in order is 58, 60, 100. We see the middle value is 60. The median of the corrected data is 60.</p>
<p>60 &gt; 58</p>
<p>The median increased.</p>
</details></li>
</ul></li>
</ul></li>
<li><p>Consider the following data set 6, 87, 100.</p>
<ul>
<li><p>Calculate the mean.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(\overline{x} = \frac{6 + 87 + 100}{3} = 64.\overline{3}\)</span></p>
<p>The mean of the data is <span class="math inline">\(64.\overline{3}\)</span>.</p>
</details></li>
<li><p>Calculate the median.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The data set in order is 6, 87, 100. We see the middle value is 87.</p>
<p>The median of the data is 87.</p>
</details></li>
<li><p>Suppose the 6 was a typo and was actually supposed to be a 60.</p>
<ul>
<li><p>What is the mean of the corrected data? Did the mean increase, decrease, or stay the same when <strong>one</strong> number in the data changed?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(\overline{x} = \frac{60 + 87 + 100}{3} = 82.\overline{3}\)</span></p>
<p>The mean of the corrected data is <span class="math inline">\(82.\overline{3}\)</span>.</p>
<p><span class="math inline">\(82.\overline{3} &gt; 64.\overline{3}\)</span></p>
<p>The mean increased.</p>
</details></li>
<li><p>What is the median of the correct data? Did the median increase, decrease, or stay the same when <strong>one</strong> number in the data changed?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The corrected data set in order is 60, 87, 100. We see the middle value is 87. The median of the corrected data is 87.</p>
<p>87 = 87</p>
<p>The median stayed the same.</p>
</details></li>
</ul></li>
</ul></li>
<li><p>Suppose you have a set of 100 exam grades and the teacher noticed that the a student’s grade recorded as a 6 was actually supposed to be a 60.</p>
<ul>
<li><p>Would changing the score from 6 to 60 cause the mean of the 100 grades to increase, decrease or stay the same?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>We saw with the toy data sets ({6, 58,100} and {6, 87, 100}) that changing the 6 to a 60 caused the mean to increase. Because 6 increased to 60 this caused the mean to increase.</p>
<p>Using this observation we see that changing the <strong>one</strong> score from 6 to 60 in the data set of 100 grades will also cause the mean to increase.</p>
</details></li>
<li><p>Would changing the score from 6 to 60 cause the median of the 100 grades to increase, decrease or stay the same?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>We saw with the toy data sets ({6, 58,100} and {6, 87, 100}) that changing the 6 to a 60 had a different effect on the median in each data set. This is because calculating the median requires that we compare the number 6 (or the corrected number 60) to every value in the data set when we order them. So we have to know the other values to know how the median is effected when we change the 6 to a 60.</p>
<p>Using this observation we see that don’t know how the median will change when we change the <strong>one</strong> score from 6 to a 60 in the 100 grades.</p>
<p>We would have to know the rest of the 100 grades to know how the median would change.</p>
</details></li>
</ul></li>
</ul>
<!--- Adapted from Practice Exam 1 --->
<!--- Winter 2023 Computation Practice #20 --->
<p>It might help students make the distinction between percentiles from a distribution verses sample percentiles if several problem sets include percentile</p>
</section>
<section id="percentile-with-distribution" class="level2">
<h2 class="anchored" data-anchor-id="percentile-with-distribution">Percentile with Distribution</h2>
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Pregnancy 80th Percentile</li>
</ul>
<p>The length of human pregnancies from conception to birth is normally distributed with mean 266 days and a standard deviation of 16 days. Find the 80th percentile.</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu =266\)</span></p>
<p><span class="math inline">\(\sigma = 16\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the <span class="math inline">\(z\)</span>-score corresponding to the 80th percentile.</p>
<ol type="1">
<li><p>Select all the area to the left.</p></li>
<li><p>Type 0.8 in the Area box.</p></li>
<li><p>Read the <span class="math inline">\(z\)</span>-score from the right box.</p></li>
</ol>
<p><img src="fig_80th_percentile.png" class="img-fluid"></p>
<p>With 80% of the area to the left, the <span class="math inline">\(z\)</span>-score is 0.842.</p>
<p><span class="math inline">\(z = 0.842\)</span></p>
<p><span class="math inline">\(\begin{aligned} x &amp;= \mu + z\sigma \\ &amp;= 266 + 0.842(16) \\ &amp;= 279.472 \end{aligned}\)</span></p>
<p>The 80th percentile is 279.5 days (<span class="math inline">\(x = 279.5\)</span>).</p>
</details>
<!--- Adapted from my 221 Wiki April 30, 2021 (Ben's exercises) --->
<!--- comment Winter 2023 Computation Practice #4 --->
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Pregnancy 90th Percentile</p>
<p>Week 4, Problem Set 1</p></li>
</ul>
<p>The length of human pregnancies from conception to birth is normally distributed with mean 266 days and a standard deviation of 16 days. Find the 90th percentile.</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 266\)</span></p>
<p><span class="math inline">\(\sigma = 16\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the <span class="math inline">\(z\)</span>-score corresponding to the 90th percentile.</p>
<ol type="1">
<li>Select all the area to the left.</li>
<li>Type 0.9 in the Area box.</li>
<li>Read the <span class="math inline">\(z\)</span>-score from the right box.</li>
</ol>
<p><img src="fig_90th_percentile.png" class="img-fluid"></p>
<p>With 90% of the area to the left, the <span class="math inline">\(z\)</span>-score is 1.282.</p>
<p><span class="math inline">\(z = 1.282\)</span></p>
<p><span class="math inline">\(\begin{align*} x &amp;= \mu + z\sigma \\ &amp;= 266 + 1.282(16) \\ &amp;= 286.512\end{align*}\)</span></p>
<p>The 90th percentile is 286.5 days (<span class="math inline">\(x = 286.5\)</span>).</p>
<pre class="excel"><code>=NORM.INV(.9,266,16)</code></pre>
</details>
<!--- Adpated from the 80th percentile problem above. --->
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Pregnancy 20th Percentile</p>
<p>Week 3, Problem Set 1</p></li>
</ul>
<p>The length of human pregnancies from conception to birth is normally distributed with mean 266 days and a standard deviation of 16 days. Find the 20th percentile.</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 266\)</span></p>
<p><span class="math inline">\(\sigma = 16\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the <span class="math inline">\(z\)</span>-score corresponding to the 20th percentile.</p>
<ol type="1">
<li>Select all the area to the left.</li>
<li>Type 0.2 in the Area box.</li>
<li>Read the <span class="math inline">\(z\)</span>-score from the left box.</li>
</ol>
<p><img src="fig_20th_percentile.png" class="img-fluid"></p>
<p>With 20% of the area to the left, the <span class="math inline">\(z\)</span>-score is -0.842.</p>
<pre class="excel"><code>=NORM.S.INV(0.2)</code></pre>
<p><span class="math inline">\(z = -0.842\)</span></p>
<p><span class="math inline">\(\begin{align*} x &amp;= \mu + z\sigma \\ &amp;= 266 + (-0.842)16 \\ &amp;= 252.528\end{align*}\)</span></p>
<p>The 20th percentile is 252.5 days (<span class="math inline">\(x = 252.5\)</span>).</p>
</details>
<!--- Adpated from the 80th percentile problem above. --->
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Pregnancy 25th Percentile</li>
</ul>
<p>The length of human pregnancies from conception to birth is normally distributed with mean 266 days and a standard deviation of 16 days. Find the 25th percentile.</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 266\)</span></p>
<p><span class="math inline">\(\sigma = 16\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the <span class="math inline">\(z\)</span>-score corresponding to the 25th percentile.</p>
<ol type="1">
<li>Select all the area to the left.</li>
<li>Type 0.25 in the Area box.</li>
<li>Read the <span class="math inline">\(z\)</span>-score from the left box.</li>
</ol>
<p><img src="fig_25th_percentile.png" class="img-fluid"></p>
<p>With 25% of the area to the left, the <span class="math inline">\(z\)</span>-score is -0.674.</p>
<p><span class="math inline">\(z = -0.674\)</span></p>
<p><span class="math inline">\(\begin{align*} x &amp;= \mu + z\sigma \\ &amp;= 266 + (-0.674)16 \\ &amp;= 255.216\end{align*}\)</span></p>
<p>The 25th percentile is 255.2 days (<span class="math inline">\(x = 255.2\)</span>).</p>
<p>The 1st quartile is 255.216 days.</p>
<pre class="excel"><code>=NORM.INV(0.25,266,16)</code></pre>
</details>
<!--- Adpated from the 80th percentile problem above. --->
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Pregnancy 50th Percentile</li>
</ul>
<p>The length of human pregnancies from conception to birth is normally distributed with mean 266 days and a standard deviation of 16 days. Find the 25th percentile.</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 266\)</span></p>
<p><span class="math inline">\(\sigma = 16\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the <span class="math inline">\(z\)</span>-score corresponding to the 25th percentile.</p>
<ol type="1">
<li>Select all the area to the left.</li>
<li>Type 0.25 in the Area box.</li>
<li>Read the <span class="math inline">\(z\)</span>-score from the left box.</li>
</ol>
<p><img src="fig_25th_percentile.png" class="img-fluid"></p>
<p>With 25% of the area to the left, the <span class="math inline">\(z\)</span>-score is -0.674.</p>
<p><span class="math inline">\(z = -0.674\)</span></p>
<p><span class="math inline">\(\begin{align*} x &amp;= \mu + z\sigma \\ &amp;= 266 + (-0.674)16 \\ &amp;= 255.216\end{align*}\)</span></p>
<p>The 25th percentile is 255.2 days (<span class="math inline">\(x = 255.2\)</span>).</p>
<p>The 1st quartile is 255.216 days.</p>
<pre class="excel"><code>=NORM.INV(0.25,266,16)</code></pre>
</details>
<!--- Adpated from the 80th percentile problem above. --->
</section>
<section id="percentile-with-data" class="level2">
<h2 class="anchored" data-anchor-id="percentile-with-data">Percentile with Data</h2>
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Sugar Sack Weights 80th percentile</li>
</ul>
<p>Use the <a href="https://tinyurl.com/M221-dist-shapes">data from tinyurl.com/M221-dist-shapes</a> to calculate the 80th percentile of sugar sack weights.</p>
<details>
<summary>
Possible Solution
</summary>
<pre class="excel"><code>=PERCENTILE(B:B,0.8)</code></pre>
<p>The 80th percentile of sugar sack weights is 10.093.</p>
</details>
<!--- Adapted from 221 Course Packet Lesson 4 exercises--->
<!--- Winter 2023 Computation Practice #5--->
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Wait Times 40th percentile</p>
<p>Week 3, Problem Set 1</p></li>
</ul>
<p>Use the <a href="https://tinyurl.com/M221-dist-shapes">data from tinyurl.com/M221-dist-shapes</a> to calculate the 40th percentile of wait times.</p>
<details>
<summary>
Possible Solution
</summary>
<pre class="excel"><code>=PERCENTILE(C:C,0.4)</code></pre>
<p>The 40th percentile of wait times is 1.8.</p>
</details>
<!--- Adpated from the Sugar Sack weights problem above. --->
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Test Scores 95 percentile</li>
</ul>
<p>Use the <a href="https://tinyurl.com/M221-dist-shapes">data from tinyurl.com/M221-dist-shapes</a> to calculate the 95th percentile of test scores.</p>
<details>
<summary>
Possible Solution
</summary>
<pre class="excel"><code>=PERCENTILE(A:A,0.95)</code></pre>
<p>The 95th percentile of test scores is 97.</p>
</details>
<!--- Adpated from the Sugar Sack weights problem above. --->
</section>
</section>
<section id="after-lesson-5" class="level1">
<h1>After Lesson 5</h1>
<section id="approximate-rule-for-bell-shaped-distributions" class="level2">
<h2 class="anchored" data-anchor-id="approximate-rule-for-bell-shaped-distributions">Approximate Rule for Bell Shaped Distributions</h2>
<p>Assign Problem 1-3 on the day of Lesson 5. I think the students should have enough information after the reading to help each other reason through these exercises.</p>
<ul>
<li><p><input type="checkbox"><strong>Problem:</strong> 68-95-99.7 Rule Problem 1</p></li>
<li><p>Use the 68-95-99.7 rule to calculate the approximate area from <span class="math inline">\(z = -1\)</span> to <span class="math inline">\(z=0\)</span>. <em>Remember the normal distribution is symmetric.</em></p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The area within 1 standard deviation of the mean is approximately 0.68.</p>
<p><img src="fig_approx_1stdev.png" class="img-fluid"></p>
<p>The distribution is symmetric so the area from <span class="math inline">\(z=0\)</span> to <span class="math inline">\(z=1\)</span> will be half of 0.68.</p>
<p>0.68/2 = 0.34</p>
<p>The area from <span class="math inline">\(z = -1\)</span> to <span class="math inline">\(z=0\)</span> will be approximately 0.34 (or 34% of the total area).</p>
<ul>
<li><p><em>What does that tell you about the area from</em> <span class="math inline">\(z = 0\)</span> <em>to</em> <span class="math inline">\(z=1\)</span><em>?</em></p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>Because the distribution is symmetric, it will be the same as the area from <span class="math inline">\(z = -1\)</span> to <span class="math inline">\(z = 0\)</span> (or 34% of the total area).</p>
</details></li>
</ul>
</details></li>
<li><p>Use the 68-95-99.7 rule to calculate the approximate below <span class="math inline">\(z=-1\)</span>.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The area within 1 standard deviation of the mean is approximately 0.68.</p>
<p><img src="fig_approx_1stdev.png" class="img-fluid"></p>
<p>The total area is 1, so the area in both tails combine will be 1-0.68 = 0.32.</p>
<p>Since the distribution is symmetric, the area in the left tail will be half of that, 0.32/2 = 0.16.</p>
<p>The area below <span class="math inline">\(z = -1\)</span> will be approximately 0.16 (or 16% of the total area).</p>
<ul>
<li><p><em>What does that tell you about the area above</em> <span class="math inline">\(z = 1\)</span><em>?</em></p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>Because the distribution is symmetric, it will be the same as the area below <span class="math inline">\(z = -1\)</span> (or 16% of the total area).</p>
</details></li>
</ul>
</details></li>
</ul>
<!-- -->
<ul>
<li><p><input type="checkbox"><strong>Problem:</strong> 68-95-99.7 Rule Problem 2</p></li>
<li><p>Use the 68-95-99.7 rule to calculate the approximate area from <span class="math inline">\(z = -2\)</span> to <span class="math inline">\(z=0\)</span>.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The area within 2 standard deviation of the mean is approximately 0.95.</p>
<p><img src="fig_approx_2stdev.png" class="img-fluid"></p>
<p>The distribution is symmetric so the area from <span class="math inline">\(z=0\)</span> to <span class="math inline">\(z=2\)</span> will be half of 0.95.</p>
<p>0.95/2 = 0.475</p>
<p>The area from <span class="math inline">\(z = -2\)</span> to <span class="math inline">\(z=0\)</span> will be approximately 0.475 (or 47.5% of the total area).</p>
<ul>
<li><p><em>What does that tell you about the area from</em> <span class="math inline">\(z = 0\)</span> <em>to</em> <span class="math inline">\(z=2\)</span><em>?</em></p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>Because the distribution is symmetric, it will be the same as the area from <span class="math inline">\(z = -2\)</span> to <span class="math inline">\(z = 0\)</span> (or 47.5% of the total area).</p>
</details></li>
</ul>
</details></li>
<li><p>Use the 68-95-99.7 rule to calculate the approximate below <span class="math inline">\(z=-2\)</span>.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The area within 2 standard deviation of the mean is approximately 0.95.</p>
<p><img src="fig_approx_2stdev.png" class="img-fluid"></p>
<p>The total area is 1, so the area in both tails combine will be 1-0.95 = 0.05.</p>
<p>Since the distribution is symmetric, the area in the left tail will be half of that, 0.05/2 = 0.025.</p>
<p>The area below <span class="math inline">\(z = -2\)</span> will be approximately 0.025 (or 2.5% of the total area).</p>
<ul>
<li><p><em>What does that tell you about the area above</em> <span class="math inline">\(z = 2\)</span><em>?</em></p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>Because the distribution is symmetric, it will be the same as the area below <span class="math inline">\(z = -2\)</span> (or 2.5% of the total area).</p>
</details></li>
</ul>
</details></li>
</ul>
<!-- -->
<ul>
<li><p><input type="checkbox"><strong>Problem:</strong> 68-95-99.7 Rule Problem 3</p></li>
<li><p>Use the 68-95-99.7 rule to calculate the approximate area from <span class="math inline">\(z = -3\)</span> to <span class="math inline">\(z=0\)</span>.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The area within 3 standard deviation of the mean is approximately 0.997.</p>
<p><img src="fig_approx_3stdev.png" class="img-fluid"></p>
<p>The distribution is symmetric so the area from <span class="math inline">\(z=0\)</span> to <span class="math inline">\(z=3\)</span> will be half of 0.997.</p>
<p>0.997/2 = 0.4985</p>
<p>The area from <span class="math inline">\(z = -3\)</span> to <span class="math inline">\(z=0\)</span> will be approximately 0.4985 (or 49.85% of the total area).</p>
<ul>
<li><p><em>What does that tell you about the area from</em> <span class="math inline">\(z = 0\)</span> <em>to</em> <span class="math inline">\(z=3\)</span><em>?</em></p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>Because the distribution is symmetric, it will be the same as the area from <span class="math inline">\(z = -3\)</span> to <span class="math inline">\(z = 0\)</span> (or 49.85% of the total area).</p>
</details></li>
</ul>
</details></li>
<li><p>Use the 68-95-99.7 rule to calculate the approximate below <span class="math inline">\(z=-3\)</span>.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The area within 3 standard deviation of the mean is approximately 0.997.</p>
<p><img src="fig_approx_3stdev.png" class="img-fluid"></p>
<p>The total area is 1, so the area in both tails combine will be 1-0.997 = 0.003.</p>
<p>Since the distribution is symmetric, the area in the left tail will be half of that, 0.003/2 = 0.0015.</p>
<p>The area below <span class="math inline">\(z = -3\)</span> will be approximately 0.0015 (or 0.15% of the total area).</p>
<ul>
<li><p><em>What does that tell you about the area above</em> <span class="math inline">\(z = 3\)</span><em>?</em></p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>Because the distribution is symmetric, it will be the same as the area below <span class="math inline">\(z = -3\)</span> (or 0.15% of the total area).</p>
</details></li>
</ul>
</details></li>
</ul>
<!-- -->
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> 68-95-99.7 Rule Problem 4</li>
</ul>
<ul>
<li><p>Use the 68-95-99.7 rule to calculate the approximate area less than <span class="math inline">\(z = -2\)</span>. Remember to draw pictures as part of your solution.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The area within 2 standard deviation of the mean is approximately 0.95.</p>
<p><img src="fig_approx_2stdev.png" class="img-fluid"></p>
<p>The remaining area is approximately 1-0.95 = 0.05.</p>
<p>Since the normal distribution is symmetric the area in the left tail (the area less than <span class="math inline">\(z = -2\)</span>) is half that, 0.05/2 = 0.025.</p>
<p>The area less than <span class="math inline">\(z = -2\)</span> is approximately 0.025 (or 2.5% of the total area).</p>
</details></li>
<li><p>Use the 68-95-99.7 rule to calculate the approximate area less than <span class="math inline">\(z = 1\)</span>. Remember to draw pictures as part of your solution.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The area within 1 standard deviation of the mean is approximately 0.68.</p>
<p><img src="fig_approx_1stdev.png" class="img-fluid"></p>
<p>The remaining area is approximately 1-0.68 = 0.32.</p>
<p>Since the distribution is symmetric the area in the left tail (the area less than <span class="math inline">\(z = -1\)</span>) is half that, 0.32/2 = 0.16.</p>
<p>The area less than <span class="math inline">\(z = 1\)</span> is the sum of the area to the left of <span class="math inline">\(z = -1\)</span> and the area between -1 and 1. We compute 0.16 + 0.68 = 0.84.</p>
<p>The area less than <span class="math inline">\(z = 1\)</span> is approximately 0.84 (or 84% of the total area).</p>
</details></li>
<li><p>Use the 68-95-99.7 rule to calculate the approximate area between <span class="math inline">\(z = -2\)</span> and <span class="math inline">\(z = 1\)</span>. Remember to draw pictures as part of your solution.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>The area we want to find is shown below.</p>
<p><img src="fig_approx_neg2to1.png" class="img-fluid"></p>
<p>If you subtract the area to the left of <span class="math inline">\(z = -2\)</span> from the area to the left of <span class="math inline">\(z = 1\)</span> you will be left with the area between <span class="math inline">\(z = -2\)</span> and <span class="math inline">\(z = 1\)</span>.</p>
<p><img src="fig_approx_neg2to1_equation.png" class="img-fluid"></p>
<p>The area to the left of <span class="math inline">\(z = -2\)</span> is 0.025 (Recall the calculation <span class="math inline">\(\frac{1 - 0.9 5}{2} = 0.025\)</span> from “part a” above).</p>
<p>The area to the left of <span class="math inline">\(z = 1\)</span> is 0.84 (Recall the calculation <span class="math inline">\(\frac{1-0.68}{2} + 0.68 = 0.84\)</span> from “part b” above).</p>
<p>Taking away the area to the left of <span class="math inline">\(z = -2\)</span> from the area to the left of <span class="math inline">\(z = 1\)</span> we have <span class="math inline">\(0.84 - 0.025 = 0.815\)</span>.</p>
<p>The area between <span class="math inline">\(z = -2\)</span> and <span class="math inline">\(z = 1\)</span> is 0.815 (or 81.5% of the total area).</p>
</details>
<p><em>Can you find a group that calculated these areas different from you? What can you learn from that group?</em></p></li>
</ul>
<!--- Winter 2023 Computation Practice #6--->
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> 68-95-99.7 Rule Problem 5</p>
<p>Week 3, Problem Set 1</p></li>
</ul>
<p>Use the 68-95-99.7 rule to calculate the approximate area between <span class="math inline">\(z = 2\)</span> and <span class="math inline">\(z = 3\)</span>. Remember to draw pictures.</p>
<details>
<summary>
Possible Solution
</summary>
<p>The area we are interested in is shown below.</p>
<p><img src="fig_approx_2to3.png" class="img-fluid"></p>
<p>The area within 3 standard deviation of the mean is approximately 0.997.</p>
<p><img src="fig_approx_3stdev.png" class="img-fluid"></p>
<p>The area within 2 standard deviation of the mean is approximately 0.95.</p>
<p><img src="fig_approx_2stdev.png" class="img-fluid"></p>
<p>If we remove (subtract) the area between <span class="math inline">\(z = -2\)</span> and <span class="math inline">\(z=2\)</span> from the area between <span class="math inline">\(z = -3\)</span> and <span class="math inline">\(z=3\)</span>, we will be left with the areas between <span class="math inline">\(z=-3\)</span> and <span class="math inline">\(z=-2\)</span> and between <span class="math inline">\(z=2\)</span> and <span class="math inline">\(z=3\)</span>.</p>
<p><img src="fig_approx_2to3_equation.png" class="img-fluid"></p>
<p>0.997 - 0.95 = 0.047</p>
<p>Because the distribution is symmetric these two remaining areas will be the same size.</p>
<p>0.047/2 = 0.0235</p>
<p>The area between <span class="math inline">\(z = 2\)</span> and <span class="math inline">\(z = 3\)</span> is 0.0235 (or 2.35% of the total area).</p>
</details>
<p><em>Can you find a group that calculated the area different from you?</em></p>
<!--- Winter 2023 Computation Practice #6d--->
<p>There is room for more Empirical Rule Problems like these.</p>
</section>
<section id="probability-calculations-with-normal-distribution" class="level2">
<h2 class="anchored" data-anchor-id="probability-calculations-with-normal-distribution">Probability Calculations with Normal Distribution</h2>
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Pregnancy</li>
</ul>
<p>The length of human pregnancies from conception to birth is normally distributed with mean 266 days and a standard deviation of 16 days.</p>
<ul>
<li><p>What is the probability a pregnancy lasts less than 242 days?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(\mu = 266\)</span></p>
<p><span class="math inline">\(\sigma = 16\)</span></p>
<p><span class="math inline">\(x = 242\)</span></p>
<p><span class="math inline">\(z = \frac{x - \mu}{\sigma} = \frac{242 - 266}{16} = -1.5\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<ol type="1">
<li>Shade the area(s) of interest.</li>
<li>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</li>
<li>Read the probability from the area box.</li>
</ol>
<p><img src="fig_pregnancy_less242.png" class="img-fluid"></p>
<p><span class="math inline">\(P(X &lt; 242) = P(Z &lt; -1.5) = 0.0668\)</span></p>
<pre class="excel"><code>=NORM.DIST(242,266,16,TRUE)</code></pre>
<p>The probability that a pregnancy lasts less than 242 days is 0.067.</p>
</details></li>
<li><p>What is the probability a pregnancy lasts less than 278 days?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(\mu = 266\)</span></p>
<p><span class="math inline">\(\sigma = 16\)</span></p>
<p><span class="math inline">\(x = 278\)</span></p>
<p><span class="math inline">\(z = \frac{x - \mu}{\sigma} = \frac{278 - 266}{16} = 0.75\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<ol type="1">
<li>Shade the area(s) of interest.</li>
<li>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</li>
<li>Read the probability from the area box.</li>
</ol>
<p><img src="fig_pregnancy_less278.png" class="img-fluid"></p>
<pre class="excel"><code>=NORM.DIST(278,266,16,TRUE)</code></pre>
<p><span class="math inline">\(P(X &lt; 278) = P(Z &lt; 0.75) = 0.7734\)</span></p>
<p>The probability that a pregnancy lasts less than 278 days is 0.773.</p>
</details></li>
<li><p>What is the probability a pregnancy lasts between 242 and 278 days?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>We are looking for the area between <span class="math inline">\(z = -1.5\)</span> and <span class="math inline">\(z = 0.75\)</span>, shown below.</p>
<p><img src="fig_pregnancy_between242and278.png" class="img-fluid"></p>
<p>We can find this area by taking away the area to the left of <span class="math inline">\(z=-1.5\)</span> from the area to the left of <span class="math inline">\(0.75\)</span>.</p>
<p><img src="fig_pregnancy_between242and278_equation.png" class="img-fluid"></p>
<p><span class="math inline">\(P(242 &lt; X &lt; 278) = P(-1.5 &lt; Z &lt; 0.75) = 0.7734 - 0.0668 = 0.7066\)</span></p>
<pre class="excel"><code>=NORM.DIST(278,266,16,TRUE) - NORM.DIST(242,266,16,TRUE)</code></pre>
<p>The probability that a pregnancy lasts between 242 and 278 days is 0.707.</p>
</details></li>
</ul>
<!--- Adapted from my 221 Wiki April 30, 2021 (Ben's exercises) --->
<!--- Winter 2023 Computation Practice #7 --->
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> LSAT</li>
</ul>
<p>The Law School Admission Test (LSAT) is required for admission to many law schools. The scores on the LSAT are approximately normal with mean of 150 and standard deviation of 9. Queen’s School of Business in Kingston, Ontario requires a minimum LSAT score of 157 for admission. What is the probability that a randomly selected student will score below 157?</p>
<details>
<summary>
Possible Solution
</summary>
<p>$= 150 $</p>
<p>$= 9 $</p>
<p><span class="math inline">\(x = 157\)</span></p>
<p><span class="math inline">\(z = \frac{x - \mu}{\sigma} = \frac{157 - 150}{9} = 0.\overline{7}\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<ol type="1">
<li>Shade the area(s) of interest.</li>
<li>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</li>
<li>Read the probability from the area box.</li>
</ol>
<p><img src="fig_LSAT.png" class="img-fluid"></p>
<pre><code>=NORM.DIST(157,150,9,TRUE)</code></pre>
<p><span class="math inline">\(P(X &lt; 157) = P(Z &lt; 0.\overline{7}) = 0.7817\)</span></p>
<p>The probability a randomly selected student will score below 157 is 0.782.</p>
</details>
<!--- comment Adapted from Lesson 7 Hmk Quiz --->
<!--- comment Winter 2023 Computation Practice #9 --->
</section>
</section>
<section id="after-lessons-6-and-7" class="level1">
<h1>After Lessons 6 and 7</h1>
<p>Note: Some calculations for Lesson 7 are the calculations used in Lesson 9.</p>
<section id="z-score-calculations" class="level2">
<h2 class="anchored" data-anchor-id="z-score-calculations"><span class="math inline">\(Z\)</span>-Score Calculations</h2>
<section id="variable-x" class="level3">
<h3 class="anchored" data-anchor-id="variable-x">Variable <span class="math inline">\(X\)</span></h3>
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> GRE</li>
</ul>
<p>Scores on the quantitative portion of the GRE are approximately normal distributed with mean <span class="math inline">\(\mu = 150.8\)</span> and a standard deviation of <span class="math inline">\(\sigma = 8.8\)</span>. Dianne earned a score of 155 on the quantitative portion of the GRE. What is the <span class="math inline">\(z\)</span>-score corresponding to Dianne’s score?</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 150.8\)</span></p>
<p><span class="math inline">\(\sigma = 8.8\)</span></p>
<p><span class="math inline">\(x = 155\)</span></p>
<p><span class="math inline">\(z = \frac{x - \mu}{\sigma} = \frac{155 - 150.8}{8.8} = 0.477273\)</span></p>
<p>The <span class="math inline">\(z\)</span>-score corresponding to Dianne’s score of 155 is <span class="math inline">\(z = 0.477\)</span>.</p>
</details>
<!--- Adapted from Lesson 7 Prep Quiz --->
<!--- Winter 2023 Computation Practice #1 --->
</section>
<section id="variable-overlinex" class="level3">
<h3 class="anchored" data-anchor-id="variable-overlinex">Variable <span class="math inline">\(\overline{X}\)</span></h3>
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> Date Money</li>
</ul>
<p>Assume that the amount of money BYU-Idaho students spend on a date is right-skewed with a mean of $16 and a standard deviation of $20. What is the <span class="math inline">\(z\)</span>-score corresponding to a random sample of 45 BYU-Idaho students with a mean of $10 spent on their last date?</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 16\)</span></p>
<p><span class="math inline">\(\sigma = 20\)</span></p>
<p><span class="math inline">\(n = 45\)</span></p>
<p><span class="math inline">\(\overline{x} = 10\)</span></p>
<p><span class="math inline">\(z = \frac{\overline{x} - \mu}{\frac{\sigma}{\sqrt{n}}} = \frac{10-16}{\frac{20}{\sqrt{45}}} = -2.01246\)</span></p>
<p>The <span class="math inline">\(z\)</span>-score corresponding to a reandom sample of 45 BYU-Idaho students with a mean of $10 spent on their last date is <span class="math inline">\(z = -2.012\)</span>.</p>
</details>
<!--- From 221 Course Packet (Lesson 7 #4; Craig's exercises) --->
<!--- Winter 2023 Computation Practice #2 --->
</section>
</section>
<section id="probability-calculations" class="level2">
<h2 class="anchored" data-anchor-id="probability-calculations">Probability Calculations</h2>
<section id="variable-x-1" class="level3">
<h3 class="anchored" data-anchor-id="variable-x-1">Variable <span class="math inline">\(X\)</span></h3>
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Reading Speed</p>
<p>Week 3, Problem Set 1</p></li>
</ul>
<p>The reading speed of second grade students is approximately normal, with a mean of 90 words per minute (wpm) and a standard deviation of 10 wpm (Sullivan, pp.&nbsp;439). What is the probability a randomly selected student will read more than 95 words per minute?</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 90\)</span></p>
<p><span class="math inline">\(\sigma = 10\)</span></p>
<p><span class="math inline">\(x = 95\)</span></p>
<p><span class="math inline">\(z = \frac{x-\mu}{\sigma} = \frac{95 - 90}{10} = 0.5\)</span></p>
<p>Normal Probability Information</p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<p>Shade the side of interest.</p>
<p>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</p>
<p>Read the probability from the area box.</p>
<p>=1-NORM.S.DIST(0.5,TRUE)</p>
<p><span class="math inline">\(P(X&gt;95) = P(Z&gt;0.5) = 0.3085\)</span></p>
<p>The probability a randomly selected student will read faster than 95 words per minute is 0.309.</p>
</details>
<!--- Adapted from my 221 Wiki May 7, 2021 --->
<!--- Winter 2023 Computation Practice #12 --->
</section>
<section id="variable-overlinex-1" class="level3">
<h3 class="anchored" data-anchor-id="variable-overlinex-1">Variable <span class="math inline">\(\overline{X}\)</span></h3>
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> GPA 1</li>
</ul>
<p>Suppose the mean GPA of BYU-Idaho students is 3.5 and the standard deviation is 0.7. It is well known that this distribution is left-skewed. What is the probability that a random sample of 70 students will have a mean GPA less than 3.6?</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 3.5\)</span></p>
<p><span class="math inline">\(\sigma = 0.7\)</span></p>
<p><span class="math inline">\(n = 70\)</span></p>
<p><span class="math inline">\(\overline{x} = 3.6\)</span></p>
<p><span class="math inline">\(z = \frac{\overline{x} - \mu}{\frac{\sigma}{\sqrt{n}}} = \frac{3.6 - 3.5}{\frac{0.7}{\sqrt{70}}} = 1.19523\)</span></p>
<p>Normal Probability Applet Information</p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<p>Shade the side of interest.</p>
<p>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</p>
<p>Read the probability from the area box.</p>
<p><span class="math inline">\(P(\overline{X} &lt; 3.6) = P(Z&lt;1.195) = 0.8840\)</span></p>
<p>=NORM.DIST(3.6, 3.5, 0.7/SQRT(70), TRUE)</p>
<p>The probability a randomly selected sample of 70 students will have a mean GPA less than 3.6 is 0.884.</p>
</details>
<!--- Adapted from Lesson 7 Prep Quiz --->
<!--- Winter 2023 Computation Practice #13 --->
<ul class="task-list">
<li><input type="checkbox"><strong>Problem:</strong> GPA</li>
</ul>
<p>Calculate the probability, if possible. If it is not possible to compute the probability explain why not.</p>
<p>Suppose the mean GPA of BYU-Idaho students is 3.5 and the standard deviation is 0.7. It is well known that this distribution is left-skewed. What is the probability that a random sample of 17 students will have a mean GPA less than 3.2?</p>
<details>
<summary>
Possible Solution
</summary>
<p>We know <span class="math inline">\(\overline{X}\)</span> is not normally distributed since <span class="math inline">\(n=17\)</span> and the population (of GPAs) is left-skewed. So we cannot calculate this probability!</p>
</details>
<!--- Adapted from Lesson 7 Prep Quiz --->
<!--- Adapted from Winter 2023 Computation Practice #14a --->
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Reading Speed (Take 2)</p>
<p>Week 3, Problem Set 1</p></li>
</ul>
<p>Calculate the probability, if possible. If it is not possible to compute the probability explain why not.</p>
<p>The reading speed of second grade students is approximately normal, with a mean of 90 words per minute (wpm) and a standard deviation of 10 wpm (Sullivan, pp.&nbsp;439). What is the probability that a random sample of 3 second grade students will have a mean reading rate less than 93 words per minute?</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 90\)</span></p>
<p><span class="math inline">\(\sigma = 10\)</span></p>
<p><span class="math inline">\(n = 3\)</span></p>
<p><span class="math inline">\(\overline{x} = 93\)</span></p>
<p><span class="math inline">\(z = \frac{\overline{x} - \mu}{\frac{\sigma}{\sqrt{n}}} = \frac{93-90}{\frac{10}{\sqrt{3}}} = 0.519615\)</span></p>
<p>Normal Probability Applet Information</p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<p>Shade the side of interest.</p>
<p>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</p>
<p>Read the probability from the area box.</p>
<p><span class="math inline">\(P(\overline{X} &lt;93) = P(Z &lt; 0.52) = 0.6985\)</span></p>
<p>=NORM.DIST(93, 90, 10/SQRT(3), TRUE)</p>
<p>The probability that a random sample of 3 second grade students will have a mean reading rate less than 93 words per minute is 0.699.</p>
</details>
<!--- Adapted from my 221 Wiki May 7, 2021 --->
<!--- Winter 2023 Computation Practice #14b --->
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Generic Sampling Distribution</p>
<p>Calculate the probability, if possible. If it is not possible to compute the probability explain why not.</p>
<p>Given data that are right-skewed, <span class="math inline">\(\mu = 5\)</span>, and <span class="math inline">\(\sigma = 2\)</span>. What is the probability a random sample of 12 will have a mean greater than 10?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p>We know <span class="math inline">\(\overline{X}\)</span> is not normally distributed since <span class="math inline">\(n=12\)</span> and the population is right-skewed. So we <strong>cannot</strong> calculate this probability!</p>
</details>
<!--- Adapted from 221 Course Packet Lesson 7 #5 (Craig's exercises) --->
<!--- Winter 2023 Computation Practice #14c ---></li>
<li><p><input type="checkbox"><strong>Problem:</strong> TV (Probability)</p>
<p>Week 4, Set 1</p></li>
</ul>
<p>The amount of time Americans spend watching television is closely monitored by A.C. Nielsen because this helps to determine advertising pricing for commercials. It is known the distribution of time Americans watch television is right skewed, with a mean of 2.35 hours per day and a standard deviation of 1.93 (Sullivan, pp.&nbsp;440). What is the probability that a random sample of 70 Americans has a mean TV viewing time greater than 1 hour per day?</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 2.35\)</span></p>
<p><span class="math inline">\(\sigma = 1.93\)</span></p>
<p><span class="math inline">\(n = 70\)</span></p>
<p><span class="math inline">\(\overline{x} = 1\)</span></p>
<p><span class="math inline">\(z = \frac{\overline{x} - \mu}{\frac{\sigma}{\sqrt{n}}} = \frac{1-2.35}{\frac{1.93}{\sqrt{70}}}=-5.85229\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<ol type="1">
<li>Shade the side of interest.</li>
<li>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</li>
<li>Read the probability from the area box.&nbsp;</li>
</ol>
<p><img src="./fig_TV.png" class="img-fluid"></p>
<pre class="excel"><code>=NORM.S.DIST(-5.852,TRUE)</code></pre>
<p><span class="math inline">\(P(\overline{X} &gt; 1) = P(Z&gt;-5.852) \approx 1\)</span></p>
<pre class="excel"><code>=NORM.DIST(1,2.35,1.93/SQRT(70),TRUE)</code></pre>
<p>The probability that the mean TV viewing time for a sample of 70 Americans is greater than 1 hour per day is very close to 1. (Note: This is a p-value, one tailed.)</p>
</details>
</section>
</section>
</section>
<section id="after-lesson-9" class="level1">
<h1>After Lesson 9</h1>
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> PH Probability and Hypothesis Test</p>
<p>Week 4, Set 2</p></li>
</ul>
<p>Part (a)</p>
<p>In a manufacturing facility, the pH of a solution must be carefully monitored. Historically, the pH values have been normally distributed with mean 3.25 and standard deviation 0.08. Find the probability that on the next test the pH of the solution will be less than 3.32.</p>
<details>
<summary>
Possible Solution
</summary>
<p><span class="math inline">\(\mu = 3.25\)</span></p>
<p><span class="math inline">\(\sigma = 0.08\)</span></p>
<p><span class="math inline">\(x = 3.32\)</span></p>
<p><span class="math inline">\(z = \frac{x - \mu}{\sigma} = \frac{3.32 - 3.25}{0.08} = 0.875\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<ol type="1">
<li>Shade the side of interest.</li>
<li>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</li>
<li>Read the probability from the area box.&nbsp;</li>
</ol>
<p><img src="fig_PH.png" class="img-fluid"></p>
<p><span class="math inline">\(P(X &lt; 3.32) = P(Z &lt; 0.875) = 0.8092\)</span></p>
<p>The probability that on the next test the pH will be less than 3.32 is 0.809.</p>
</details>
<!--- From 221 Course Packet (Lesson 8 #15; Craig's exercises) --->
<!--- Winter 2023 Computation Practice #10 --->
<p>Part (b)</p>
<p>In a manufacturing facility, the pH of a solution must be carefully monitored. Historically, the pH values have been normally distributed with mean 3.25 and standard deviation 0.08. The quality control department wants to test whether the true mean pH is less than 3.25. They will use the next sample to complete this test. The next sample has a pH of 3.32.</p>
<details>
<summary>
Possible Solution
</summary>
<p><strong>Null and alternative hypotheses</strong></p>
<p><span class="math inline">\(H_0: \mu = 3.25\)</span></p>
<p><span class="math inline">\(H_a: \mu &lt; 3.25\)</span></p>
<p><strong>Level of significance</strong></p>
<p><span class="math inline">\(\alpha = 0.05\)</span></p>
<p><strong>Summary statistics</strong></p>
<p><span class="math inline">\(x = 3.32\)</span></p>
<p>Assume <span class="math inline">\(\sigma = 0.08\)</span></p>
<p><strong>Test statistic</strong><span class="math inline">\(z = \frac{x - \mu}{\sigma} = \frac{3.32-3.25}{0.08} = 0.875\)</span></p>
<p><em>Note: This is the same as</em> <span class="math inline">\(z = \frac{\overline{x} - \mu}{\frac{\sigma}{\sqrt{n}}} = \frac{3.32 - 3.25}{\frac{0.08}{\sqrt{1}}} = 0.875\)</span><em>.</em></p>
<p><strong>P-value and comparison to</strong> <span class="math inline">\(\alpha\)</span></p>
<p>Because the alternative hypothesis is <span class="math inline">\(\mu &lt; 3.25\)</span> we are looking for the probability of being less than the test statistic.</p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<ol type="1">
<li>Shade the side of interest.</li>
<li>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</li>
<li>Read the probability from the area box.&nbsp;</li>
</ol>
<p><img src="fig_PH.png" class="img-fluid"></p>
<p><span class="math inline">\(P(X &lt; 3.32) = P(Z &lt; 0.875) = 0.8092\)</span></p>
<p><span class="math inline">\(p\)</span>-value = 0.809 &gt; 0.05 = <span class="math inline">\(\alpha\)</span></p>
<p><strong>Conclusion</strong></p>
<p>We <u>fail to reject</u> the null hypothesis.</p>
<p><strong>English Sentence</strong></p>
<p>There is <u>insufficient</u> evidence to suggest that the mean pH is less than 3.25.</p>
</details>
<!--- Adapted from Winter 2023 Computation Practice # 10 --->
<!--- Adapted from 221 Course Packet (Lesson 8 #15; Craig's exercises) --->
<!--- Notice this problem is presented as a probability question and as a hypothesis test question. Give at the same time -- try to help students make the connections. --->
<p>Part (c)</p>
<p>Compare the previous two parts. The first part is a probability question. The second part is a hypothesis test question. What similarities do you notice?</p>
<details>
<summary>
Possible Solution
</summary>
<p>The probability calculation in the first part is the same calculation in the Test Statistic and p-value calculations of the hypothesis in the second part.</p>
</details>
</section>
<section id="after-lesson-10" class="level1">
<h1>After Lesson 10</h1>
<section id="sample-size-calculations" class="level2">
<h2 class="anchored" data-anchor-id="sample-size-calculations">Sample Size Calculations</h2>
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Blinks</p>
<p>Suppose you are scientist and you want to use a confidence interval to estimate the true mean number of times a person in your city blinks each day. Find the sample size required to construct a 90% confidence interval with a margin of error 43 blinks for the true mean number of time a person blinks each day. Assume the standard deviation of blinks per day is 1240.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(z^* = 1.645\)</span> (because we want a confidence level of 90%)</p>
<p><span class="math inline">\(m = 43\)</span></p>
<p><span class="math inline">\(\sigma = 1240\)</span></p>
<p><span class="math inline">\(n = \left(\frac{z^* \sigma}{m}\right)^2 = \left(\frac{(1.645)(1240)}{1240}\right)^2 = 2250.29\)</span></p>
<p>We need a sample size of at least 2251. <em>Remember to round up to the next integer with sample size calculations.</em></p>
</details>
<!--- Adapted from Lesson 17 Hmk Quiz --->
<!--- Winter 2023 Computation Practice #18 ---></li>
</ul>
</section>
</section>
<section id="after-lesson-16" class="level1">
<h1>After Lesson 16</h1>
<p>Note: Some calculations for Lesson 16 are the calculations used in Lesson 17.</p>
<section id="z-score-calculations-1" class="level2">
<h2 class="anchored" data-anchor-id="z-score-calculations-1"><span class="math inline">\(Z\)</span>-Score Calculations</h2>
<section id="variable-hatp" class="level3">
<h3 class="anchored" data-anchor-id="variable-hatp">Variable <span class="math inline">\(\hat{P}\)</span></h3>
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Soccer</p>
<p>John is a soccer player. He knows that he scores a goal 60% of the time. What is the <span class="math inline">\(z\)</span>-score corresponding to John scoring 51 of 78 attempted goals?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(p = 0.6\)</span></p>
<p><span class="math inline">\(x = 51\)</span></p>
<p><span class="math inline">\(n = 78\)</span></p>
<p><span class="math inline">\(\hat{p} = \frac{x}{n} = \frac{51}{78} = 0.653846\)</span><br>
<span class="math inline">\(\begin{align*} z &amp;= \frac{\hat{p} - p}{\sqrt{\frac{p(1-p)}{n}}} \\ &amp;= \frac{(51/78) - 0.6}{\sqrt{\frac{0.6(0.4)}{78}}} \\ &amp;= 0.970725 \end{align*}\)</span></p>
<p>The <span class="math inline">\(z\)</span>-score corresponding to John scoring 51 of 78 attempted goals is <span class="math inline">\(z = 0.971\)</span>.</p>
</details>
<!--- Adapted from my 221 Wiki June 16, 2021 (Ben's exercises) --->
<!--- Winter 2023 Computation Practice #3 ---></li>
</ul>
</section>
</section>
<section id="probability-calculations-1" class="level2">
<h2 class="anchored" data-anchor-id="probability-calculations-1">Probability Calculations</h2>
<section id="variable-hatp-1" class="level3">
<h3 class="anchored" data-anchor-id="variable-hatp-1">Variable <span class="math inline">\(\hat{P}\)</span></h3>
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Phishing Emails</p>
<p>First Data Corp.&nbsp;records indicate that in 2005, 43% of adult email users received a phishing email. A phishing email replicates an authentic site for the purpose of stealing personal information such as account numbers and passwords. Suppose a random sample of 400 adults will be surveyed on whether they have received phishing emails to determine recent trends. What is the probability that more than 38% of those in such a survey would have received a phishing email?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(p = 0.43\)</span></p>
<p><span class="math inline">\(n = 400\)</span></p>
<p><span class="math inline">\(\hat{p} = 0.38\)</span></p>
<p><span class="math inline">\(z = \frac{\hat{p}-p}{\sqrt{\frac{p(1-p)}{n}}} = \frac{0.38-0.43}{\sqrt{\frac{0.43(1-0.43)}{400}}} = -2.01989\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<ol type="1">
<li>Shade the side of interest.</li>
<li>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</li>
<li>Read the probability from the area box.&nbsp;</li>
</ol>
<p><img src="fig_PhishingEmail.png" class="img-fluid"></p>
<p><span class="math inline">\(P(\hat{P} &gt; 0.38) = P(Z &gt; -2.01989) = 0.9783\)</span></p>
<pre class="excel"><code>=1-NORM.DIST(0.38,0.43,SQRT(0.43*(1-0.43)/400),TRUE)</code></pre>
<p>The probability that more than 38% of respondents in such a survey would have received a phishing email is 0.978.</p>
</details>
<!--- From Lesson 16 Homework; numbers changed. --->
<!--- Winter 2023 Computation Practice #8  ---></li>
</ul>
<!-- -->
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Stock Market</p>
<p>You take a simple random sample of 200 adults from a town in the Western United States to determine the proportion of those in town who invest in the stock market. Assume the unknown population proportion or percentage of people in town who invest in the stock market is (or 30%). What is the probability that more than 25% of those in such a survey would have invested in the stock market?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(p = 0.3\)</span></p>
<p><span class="math inline">\(n = 200\)</span></p>
<p><span class="math inline">\(\hat{p} = 0.25\)</span></p>
<p><span class="math inline">\(z = \frac{\hat{p}-p}{\sqrt{\frac{p(1-p)}{n}}} = \frac{0.25-0.3}{\sqrt{\frac{0.3(0.7)}{200}}} = -1.54303\)</span></p>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<ol type="1">
<li>Shade the side of interest.</li>
<li>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</li>
<li>Read the probability from the area box.&nbsp;</li>
</ol>
<p><img src="fig_StockMarket.png" class="img-fluid"></p>
<p><span class="math inline">\(P(\hat{P} &gt; 0.25) = P(Z &gt; -1.543) = 0.9386\)</span></p>
<pre class="excel"><code>=1-NORM.DIST(0.25,0.3,SQRT(0.3*(0.7)/200),TRUE)</code></pre>
<p>The probability that more than 38% of respondents in such a survey would have received a phishing email is 0.978.</p>
</details>
<!--- Adapted from Practice Exam 3; numbers and wording changed slightly --->
<!--- Winter 2023 Computation Practice #11 ---></li>
<li><p><input type="checkbox"><strong>Problem:</strong> Smoking Teens</p>
<p>Calculate the probability, if possible. If it is not possible to compute the probability explain why not.</p>
<p>A study was conducted to determine the proportion of American teenagers who smoke. Previous surveys showed that 15% percent of teenagers smoke. A Gallup survey interviewed a nationally representative sample of 785 teenagers. What is the probability less than 97 teenagers in the survey smoke?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(p = 0.15\)</span></p>
<p><span class="math inline">\(n = 785\)</span></p>
<p><span class="math inline">\(np = 785(0.15) = 117.75 \geq 10\)</span> (check!)</p>
<p><span class="math inline">\(n(1-p) = 785(1-0.15) = 667.25 \geq 10\)</span> (check!)</p>
<p><span class="math inline">\(x = 97\)</span></p>
<p><span class="math inline">\(\hat{p} = \frac{x}{n} = \frac{97}{785} = 0.123567\)</span></p>
<p><span class="math inline">\(z = \frac{\hat{p} - p}{\sqrt{\frac{p(1-p)}{n}}} = \frac{\frac{97}{785} - 0.15}{\sqrt{\frac{0.15(1-0.15)}{785}}} = -2.07409\)</span></p>
<pre class="excel"><code>=((97/785) - 0.15)/SQRT(0.15*(1-0.15)/785)</code></pre>
<p><strong>Normal Probability Applet Information</strong></p>
<p>To find the probability corresponding to a <span class="math inline">\(z\)</span>-score.</p>
<ol type="1">
<li>Shade the side of interest.</li>
<li>Type the <span class="math inline">\(z\)</span>-score in the box (negative value the left box and positive values the right box).</li>
<li>Read the probability from the area box.</li>
</ol>
<p><img src="fig_SmokingTeens.png" class="img-fluid"></p>
<p><span class="math inline">\(P(X &lt; 97) = P(\hat{P} &lt; 0.124) = P(Z &lt; -2.074) = 0.0190\)</span></p>
<pre class="excel"><code>=NORM.DIST(97/785, 0.15, SQRT(0.15*(1-0.15)/785), TRUE)</code></pre>
<p>The probability less than 97 teenagers in the survey smoke is 0.019.</p>
</details>
<!--- Adapted from Lesson 17 Hmk Quiz --->
<!--- Revised from Winter 2023 Computation Practice #14d ---></li>
<li><p><input type="checkbox"><strong>Problem:</strong> COVID</p>
<p>Calculate the probability, if possible. If it is not possible to compute the probability explain why not.</p>
<p>Data from the Centers for Disease Control and Prevention shows that among the people in the United States who are fully vaccinated, the probability of getting COVID is very, very small: only 0.0001. Suppose you plan to survey 50,000 people (<span class="math inline">\(n=50000\)</span>) who are fully vaccinated to see if they contracted COVID after getting the vaccine. What is the probability that less than 10 of the fully vaccinated people you survey contracted COVID after getting the vaccine?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(p = 0.0001\)</span></p>
<p><span class="math inline">\(n = 50000\)</span></p>
<p><span class="math inline">\(np = 50000(0.0001) = 5 \ngeq 10\)</span></p>
<p>Since <span class="math inline">\(np \neq 10\)</span> we see <span class="math inline">\(\hat{P}\)</span> is not normally distributed. So we <strong>cannot</strong> calculate this probability!</p>
</details>
<!--- Originally from 221 Course Packet (Lesson 16 #11; Craig's exercises) --->
<!--- Adapted from Winter 2023 Computation Practice #15 ---></li>
</ul>
</section>
</section>
<section id="sample-size" class="level2">
<h2 class="anchored" data-anchor-id="sample-size">Sample Size</h2>
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Generic Sampling Distribution Check</p>
<p>Given the true proportion is <span class="math inline">\(p = 0.1\)</span>. What is the smallest value of <span class="math inline">\(n\)</span> that satisfies the requirements for the random variable <span class="math inline">\(\hat{p}\)</span> to be normally distributed?</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(p = 0.1\)</span></p>
<p><span class="math inline">\(\begin{align*}np &amp;\geq 10 \\n(0.1) &amp;\geq 10 \\n &amp;\geq \frac{10}{0.1} = 100 \\n &amp;\geq 100\end{align*}\)</span></p>
<p><span class="math inline">\(\begin{align*} n(1-p) &amp;\geq 10 \\ n(0.9) &amp;\geq 10 \\ n &amp;\geq \frac{10}{0.9} = 11.\overline{1} \\ n &amp;\geq 11.\overline{1} \end{align*}\)</span></p>
<p>Since both <span class="math inline">\(np\)</span> and <span class="math inline">\(n(1-p)\)</span> are greater than 10 when <span class="math inline">\(n \geq 100\)</span>, we see that the smallest value of <span class="math inline">\(n\)</span> so that <span class="math inline">\(\hat{P}\)</span> is normally distributed is <span class="math inline">\(n=100\)</span>.</p>
</details>
<!--- Adapted from Lesson 16 Prep Quiz and Lesson 16 Homework Quiz --->
<!--- Winter 2023 Computation Practice #16 ---></li>
</ul>
</section>
</section>
<section id="after-lesson-17" class="level1">
<h1>After Lesson 17</h1>
<section id="sample-size-1" class="level2">
<h2 class="anchored" data-anchor-id="sample-size-1">Sample Size</h2>
<ul class="task-list">
<li><p><input type="checkbox"><strong>Problem:</strong> Doctors</p>
<p>A survey of doctors is planned to see what percentage prescribe a certain medication. Find the sample size required to achieve a 5% margin of error if the confidence level is 90%.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(z^* = 1.645\)</span> (because we want a confidence level of 90%)</p>
<p><span class="math inline">\(m = 0.05\)</span></p>
<p><span class="math inline">\(n = \left(\frac{z^*}{2m}\right)^2 = \left(\frac{1.645}{2(0.05)}\right)^2 = 270.603\)</span></p>
<p>We need a sample size of at least 271. <em>Remember to round up to the next integer with sample size calculations.</em></p>
</details>
<!--- Adapted from Lesson 17 Hmk Quiz--->
<!--- Winter 2023 Computation Practice #17 ---></li>
<li><p><input type="checkbox"><strong>Problem:</strong> Dow Jones Industrial Average</p>
<p>A recent book noted that only 20% of all investment managers outperform the Dow Jones Industrial Average over a five-year period. Suppose you are in charge of designing the study. What sample size would be needed to construct a 98% confidence interval with a margin of error 3%.</p>
<details>
<summary>
<p>Possible Solution</p>
</summary>
<p><span class="math inline">\(p^* = 0.2\)</span></p>
<p><span class="math inline">\(z^* = 2.326\)</span> (because we want a confidence level of 98%)</p>
<p><span class="math inline">\(m = 0.03\)</span></p>
<p><span class="math inline">\(n = \left( \frac{z^*}{m} \right)^2 p^*(1 - p^*) = \left(\frac{2.326}{0.03}\right)^2(0.02)(0.8) = 961.827\)</span></p>
<p>We need a sample size of at least 962. <em>Remember to round up to the next integer with sample size calculations.</em></p>
</details>
<!--- Adapted from Practice Exam 3 --->
<!--- Winter 2023 Computation Practice #19 ---></li>
</ul>
</section>
</section>
<section id="after-lesson-22" class="level1">
<h1>After Lesson 22</h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>